# Generated by Django 5.1.4 on 2025-01-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("mob", models.TextField()),
                ("add", models.TextField()),
            ],
        ),
    ]
