# Generated by Django 5.1.5 on 2025-01-21 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_userregister_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userregister",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="empcode",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="empdept",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="joiningdate",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="user",
        ),
        migrations.AddField(
            model_name="userregister",
            name="add",
            field=models.TextField(default="Default Address"),
        ),
        migrations.AddField(
            model_name="userregister",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="mob",
            field=models.CharField(
                default="1234567890",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_mobile",
                        message="Mobile number must be 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="userregister",
            name="name",
            field=models.CharField(default="Default Name", max_length=50),
        ),
        migrations.AddField(
            model_name="userregister",
            name="password",
            field=models.CharField(default="default_password", max_length=50),
        ),
        migrations.CreateModel(
            name="employeedetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empcode", models.CharField(max_length=50, null=True)),
                ("empdept", models.CharField(max_length=100, null=True)),
                ("destination", models.CharField(max_length=100, null=True)),
                ("contact", models.CharField(max_length=15, null=True)),
                ("gender", models.CharField(max_length=50, null=True)),
                ("joiningdate", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.userregister",
                    ),
                ),
            ],
        ),
    ]
