# Generated by Django 5.1.5 on 2025-01-21 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_userregister_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetails",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.userregister",
            ),
        ),
    ]
